steps:
- name: node:14
  entrypoint: yarn
  args: ['install']
- name: node:14
  entrypoint: yarn
  args: ['run', 'build']
  env:
  - 'REACT_APP_APARTMENTS_API_URL=https://europe-central2-salamlab-aparatments.cloudfunctions.net/'
  - 'REACT_APP_APARTMENTS_ROUTER_BASENAME='
  - 'REACT_APP_APARTMENTS_API_USE_MOCKS=false'
