steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - config
      - set
      - "@fortawesome:registry"
      - https://npm.fontawesome.com/
    entrypoint: npm
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - config
      - set
      - "//npm.fontawesome.com/:_authToken"
      - $$FONTAWESOME_TOKEN
    entrypoint: npm
    secretEnv: ['FONTAWESOME_TOKEN']
  - name: 'node:14-alpine'
    args:
      - install
    entrypoint: yarn
  - name: 'node:14-alpine'
    env:
      - REACT_APP_KOKON_API_URL=https://europe-central2-salamlab-aparatments.cloudfunctions.net/
      - REACT_APP_KOKON_ROUTER_BASENAME=
      - REACT_APP_KOKON_API_USE_MOCKS=true
      - REACT_APP_KOKON_API_DEBUG_FETCH_DELAY=0
    args:
      - run
      - build
    entrypoint: yarn
  - name: 'alpine:3.15.0'
    args:
      - touch
      - dummy.txt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - cp
      - dummy.txt
      - 'gs://salamlab-apartments_frontend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - rm
      - '-rf'
      - 'gs://salamlab-apartments_frontend/*'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - cp
      - '-r'
      - build/*
      - 'gs://salamlab-apartments_frontend'
timeout: 600s
availableSecrets:
  secretManager:
    - versionName: projects/396614679188/secrets/fontawesome_token/versions/1
      env: 'FONTAWESOME_TOKEN'