steps:
  - name: 'node:14-alpine'
    args:
      - install
    entrypoint: yarn
  - name: 'node:14-alpine'
    env:
      - REACT_APP_KOKON_API_URL=https://europe-central2-salamlab-aparatments.cloudfunctions.net/
      - REACT_APP_KOKON_ROUTER_BASENAME=
      - REACT_APP_KOKON_API_USE_MOCKS=false
    args:
      - run
      - build
    entrypoint: yarn
  - name: 'alpine:3.15.0'
    args:
      - touch
      - dummy.txt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - cp
      - dummy.txt
      - 'gs://salamlab-apartments_frontend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - rm
      - '-rf'
      - 'gs://salamlab-apartments_frontend/*'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-alpine'
    args:
      - gsutil
      - cp
      - '-r'
      - build/*
      - 'gs://salamlab-apartments_frontend'
timeout: 600s