export const GuestPriorityStatus = Object.freeze({
    ACCOMMODATION_FOUND: "ACCOMMODATION_FOUND",
    ACCOMMODATION_NOT_NEEDED: "ACCOMMODATION_NOT_NEEDED",
    AT_R3: "AT_R3",
    DOES_NOT_RESPOND: "DOES_NOT_RESPOND",
    EN_ROUTE_POLAND: "EN_ROUTE_PL",
    EN_ROUTE_UKRAINE: "EN_ROUTE_UA",
    IN_KRAKOW: "IN_KRK",
    UPDATED: "UPDATED",
});
